apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  labels:
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/workload-name: acme-catalog
    carto.run/workload-namespace: my-apps
  name: acme-catalog
  namespace: my-apps
spec:
  source:
    image: tapacr.azurecr.io/evana-tap-for-tsm/apps-14-09-2022-16-30-49-220453313/acme-catalog-my-apps-bundle:727d9411-ce74-4dd0-90a6-640add35cbc9
