apiVersion: carto.run/v1alpha1 # for versions before 1.8.0 use apps/v1beta1
kind: Workload
metadata:
  name: acme-pos
  labels:
    apps.tanzu.vmware.com/workload-type: server
    apps.tanzu.vmware.com/has-tests: "true"  # Needed for test and scan-test supply chains
spec:
  source:
    git:
      url: https://github.com/evankanderson/acme-fitness-store
      ref:
        branch: Azure
    subPath: apps/acme-shopping
  params:
  - name: ports
    value:
      - containerPort: 7777
        name: cart
        port: 7777
  env:
  - name: HTTP_PORT
    value: '7777'
  - name: DATASTORE
    value: 'REMOTE'
  - name: FRONTEND_HOST
    value: 'acme-frontend'
