apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: acme-fitness
  labels:
    apps.tanzu.vmware.com/workload-type: server
spec:
  source:
    git:
      url: https://github.com/evankanderson/acme-fitness-store
      ref:
        branch: Azure
    subPath: apps/acme-catalog
